import { db } from './db';
import type { Exercise } from './schema';

export interface SeedExerciseInput extends Omit<Exercise, 'id' | 'substituteIds'> {
  substituteSlugs: string[];
}

const EXERCISES_SEED: SeedExerciseInput[] = [
  // ===== CHEST (5) =====
  {
    slug: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['incline-dumbbell-press', 'dumbbell-chest-fly', 'push-up', 'chest-dip'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Lie flat on bench, eyes under bar. Grip slightly wider than shoulder-width. Retract shoulder blades into bench.',
      execution: 'Lower bar with control (2-3s) to mid-chest. Press back up to lockout without losing shoulder blade tension.',
      commonMistakes: 'Bouncing bar off chest, flaring elbows to 90 degrees, lifting hips off bench.',
      breathingCues: 'Inhale on the way down, exhale forcefully as you press up.',
    },
  },
  {
    slug: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['barbell-bench-press', 'dumbbell-chest-fly', 'push-up'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Set bench to 30-45 degrees. Kick dumbbells up to shoulder level with knees.',
      execution: 'Press dumbbells overhead in a gentle arc. Lower under control to upper chest level.',
      commonMistakes: 'Incline set too steep (becomes shoulder press), letting shoulders roll forward at bottom.',
      breathingCues: 'Inhale on descent, exhale on press.',
    },
  },
  {
    slug: 'dumbbell-chest-fly',
    name: 'Dumbbell Chest Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['cable-crossover', 'incline-dumbbell-press', 'barbell-bench-press'],
    weightIncrementKg: 2.0,
    techniqueNotes: {
      setup: 'Lie flat on bench. Hold dumbbells over chest with slight fixed bend in elbows.',
      execution: 'Lower in a wide arc until chest stretch is felt. Squeeze back together like hugging a tree.',
      commonMistakes: 'Bending elbows excessively (making it a press), dropping arms too low below bench level.',
      breathingCues: 'Inhale on opening arc, exhale squeezing together.',
    },
  },
  {
    slug: 'cable-crossover',
    name: 'Cable Crossover',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteSlugs: ['dumbbell-chest-fly', 'incline-dumbbell-press', 'push-up'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Set pulleys at chest height. Step forward into staggered stance with slight torso forward lean.',
      execution: 'Bring handles together in front of lower chest in a hugging motion, crossing wrists slightly.',
      commonMistakes: 'Using momentum, locking elbows completely straight.',
      breathingCues: 'Exhale bringing handles together, inhale returning.',
    },
  },
  {
    slug: 'chest-dip',
    name: 'Chest Dip',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    difficultyTier: 'intermediate',
    substituteSlugs: ['barbell-bench-press', 'incline-dumbbell-press', 'push-up'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Grip dip bars, support bodyweight. Lean torso forward ~30 degrees to bias chest over triceps.',
      execution: 'Lower until shoulders are slightly below elbows. Drive back up to lockout.',
      commonMistakes: 'Staying completely upright (hits triceps), shrugging shoulders up.',
      breathingCues: 'Inhale descending, exhale pressing up.',
    },
  },

  // ===== BACK (7) =====
  {
    slug: 'barbell-bent-over-row',
    name: 'Barbell Bent-Over Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['dumbbell-single-arm-row', 'lat-pulldown', 'seated-cable-row', 't-bar-row'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Hinge at hips to ~45 degrees, neutral spine, overhand grip slightly wider than shoulders.',
      execution: 'Pull bar to lower chest / upper belly, driving elbows back. Lower under control.',
      commonMistakes: 'Rounding lower back, standing up using momentum.',
      breathingCues: 'Exhale on pull, inhale lowering.',
    },
  },
  {
    slug: 'dumbbell-single-arm-row',
    name: 'Dumbbell Single-Arm Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['barbell-bent-over-row', 'seated-cable-row', 'lat-pulldown'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Support knee and hand on flat bench. Dumbbell in opposite hand, arm hanging straight.',
      execution: 'Pull dumbbell to hip crease, driving elbow toward ceiling. Lower to full stretch.',
      commonMistakes: 'Rotating torso excessively, shrugging shoulder up.',
      breathingCues: 'Exhale pulling up, inhale lowering.',
    },
  },
  {
    slug: 'lat-pulldown',
    name: 'Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteSlugs: ['pull-up', 'seated-cable-row', 'barbell-bent-over-row'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Grip bar wide, thighs secured under pad, slight lean back (~15 degrees).',
      execution: 'Pull bar to upper chest, squeezing lats down and back. Control the return to full overhead stretch.',
      commonMistakes: 'Pulling behind neck, leaning back excessively.',
      breathingCues: 'Exhale on pull, inhale on rise.',
    },
  },
  {
    slug: 'pull-up',
    name: 'Pull-Up',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    difficultyTier: 'intermediate',
    substituteSlugs: ['lat-pulldown', 'seated-cable-row', 'dumbbell-single-arm-row'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Overhand grip slightly wider than shoulders on pull-up bar from dead hang.',
      execution: 'Pull chin above bar by driving elbows down. Lower to full dead hang.',
      commonMistakes: 'Kipping/swinging legs, partial range at bottom.',
      breathingCues: 'Exhale pulling up, inhale lowering down.',
    },
  },
  {
    slug: 'seated-cable-row',
    name: 'Seated Cable Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteSlugs: ['barbell-bent-over-row', 'dumbbell-single-arm-row', 'lat-pulldown'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Feet on pads, knees slightly bent, hold v-bar attachment with upright spine.',
      execution: 'Pull handle to abdomen while driving shoulder blades together. Return with control.',
      commonMistakes: 'Swinging torso back and forth excessively.',
      breathingCues: 'Exhale pulling in, inhale extending.',
    },
  },
  {
    slug: 'face-pull',
    name: 'Face Pull',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteSlugs: ['rear-delt-dumbbell-fly', 'dumbbell-lateral-raise'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Attach rope at eye level on cable machine. Grip rope with thumbs pointing back.',
      execution: 'Pull rope toward forehead, flaring hands out past ears in double-bicep pose.',
      commonMistakes: 'Too heavy weight, pulling to throat instead of face.',
      breathingCues: 'Exhale pulling back, inhale returning.',
    },
  },
  {
    slug: 't-bar-row',
    name: 'T-Bar Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['barbell-bent-over-row', 'seated-cable-row', 'dumbbell-single-arm-row'],
    weightIncrementKg: 5.0,
    techniqueNotes: {
      setup: 'Straddle T-bar machine or landmine, grip handles with flat lower back bent ~45 deg.',
      execution: 'Row weight up to chest, pulling shoulder blades together. Lower under control.',
      commonMistakes: 'Jerking hips to bounce weight up.',
      breathingCues: 'Exhale on pull, inhale lowering.',
    },
  },

  // ===== SHOULDERS (5) =====
  {
    slug: 'overhead-press-barbell',
    name: 'Overhead Press (Barbell)',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['arnold-press', 'machine-shoulder-press', 'dumbbell-lateral-raise'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Grip bar shoulder-width, resting across front deltoids. Core and glutes braced.',
      execution: 'Press bar straight overhead until elbows lock out. Head moves forward slightly at top.',
      commonMistakes: 'Arching lower back excessively, pressing bar out in front instead of straight up.',
      breathingCues: 'Brace core before press, exhale at lockout overhead.',
    },
  },
  {
    slug: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['cable-lateral-raise', 'arnold-press', 'face-pull'],
    weightIncrementKg: 1.0,
    techniqueNotes: {
      setup: 'Stand holding dumbbells at sides, slight bend in elbows, slight forward lean.',
      execution: 'Raise arms out to sides until parallel with floor. Lead with elbows, pinkies slightly higher.',
      commonMistakes: 'Swinging weight with hips, shrugging upper traps.',
      breathingCues: 'Exhale raising up, inhale lowering.',
    },
  },
  {
    slug: 'rear-delt-dumbbell-fly',
    name: 'Rear Delt Dumbbell Fly',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['face-pull', 'dumbbell-lateral-raise'],
    weightIncrementKg: 1.0,
    techniqueNotes: {
      setup: 'Hinge forward 90 degrees at hips or sit on bench edge bent forward over thighs.',
      execution: 'Raise dumbbells out to sides in wide arc, focusing on posterior deltoids.',
      commonMistakes: 'Bending elbows into a row, swinging torso.',
      breathingCues: 'Exhale raising, inhale lowering.',
    },
  },
  {
    slug: 'arnold-press',
    name: 'Arnold Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['overhead-press-barbell', 'machine-shoulder-press', 'dumbbell-lateral-raise'],
    weightIncrementKg: 2.0,
    techniqueNotes: {
      setup: 'Sit upright on bench. Hold dumbbells at collarbone level with palms facing you.',
      execution: 'Rotate palms outward as you press overhead until palms face away at top.',
      commonMistakes: 'Rushing rotation, arching lower back.',
      breathingCues: 'Exhale pressing up, inhale lowering.',
    },
  },
  {
    slug: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteSlugs: ['overhead-press-barbell', 'arnold-press', 'dumbbell-lateral-raise'],
    weightIncrementKg: 5.0,
    techniqueNotes: {
      setup: 'Adjust seat so handles align with shoulder height. Back firmly against pad.',
      execution: 'Press handles overhead to lockout without locking elbows hard. Lower with control.',
      commonMistakes: 'Flaring elbows outward, arching lower back away from pad.',
      breathingCues: 'Exhale pressing up, inhale returning.',
    },
  },
  {
    slug: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteSlugs: ['dumbbell-lateral-raise', 'face-pull'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Stand next to low pulley. Grip handle across body with opposite hand.',
      execution: 'Raise arm out to side to shoulder height under constant cable tension.',
      commonMistakes: 'Shrugging trap, leaning away excessively.',
      breathingCues: 'Exhale raising, inhale lowering.',
    },
  },

  // ===== QUADS (5) =====
  {
    slug: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['leg-press', 'bulgarian-split-squat', 'goblet-squat'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Bar across upper traps, feet shoulder-width apart, toes turned slightly out.',
      execution: 'Sit back and down until hip crease is below top of knees. Drive up through heels.',
      commonMistakes: 'Knees caving inward, heels lifting off floor.',
      breathingCues: 'Inhale & brace core at top, hold down, exhale coming up.',
    },
  },
  {
    slug: 'leg-press',
    name: 'Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteSlugs: ['barbell-back-squat', 'leg-extension', 'goblet-squat'],
    weightIncrementKg: 5.0,
    techniqueNotes: {
      setup: 'Sit in leg press machine, feet shoulder-width at mid-height on sled platform.',
      execution: 'Lower sled until knees reach 90 degrees. Press back up without locking knees hard.',
      commonMistakes: 'Locking knees hard at top, lower back lifting off backrest.',
      breathingCues: 'Inhale lowering sled, exhale pushing.',
    },
  },
  {
    slug: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['barbell-back-squat', 'goblet-squat', 'leg-press'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Back foot elevated on bench behind you, front foot stepped out 2-3 feet.',
      execution: 'Lower back knee toward floor while keeping torso upright. Drive up through front heel.',
      commonMistakes: 'Front knee pushing too far forward past toes.',
      breathingCues: 'Inhale lowering down, exhale driving up.',
    },
  },
  {
    slug: 'leg-extension',
    name: 'Leg Extension',
    primaryMuscle: 'quads',
    secondaryMuscles: [],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteSlugs: ['leg-press', 'barbell-back-squat'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Sit in machine with shin pad against lower legs, knees aligned with machine pivot.',
      execution: 'Extend legs straight out, squeezing quads hard at peak extension. Lower slowly.',
      commonMistakes: 'Kicking weight up with momentum, partial extension.',
      breathingCues: 'Exhale extending, inhale lowering.',
    },
  },
  {
    slug: 'goblet-squat',
    name: 'Goblet Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['barbell-back-squat', 'leg-press', 'bulgarian-split-squat'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Hold one dumbbell vertically against chest with both hands. Feet shoulder-width.',
      execution: 'Squat down between knees until thighs are parallel to floor. Stand tall.',
      commonMistakes: 'Rounding upper back under dumbbell weight.',
      breathingCues: 'Inhale descending, exhale standing up.',
    },
  },

  // ===== HAMSTRINGS & GLUTES (7) =====
  {
    slug: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['dumbbell-romanian-deadlift', 'leg-curl-machine', 'hip-thrust-barbell'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Stand holding bar at hip height, feet hip-width, knees slightly soft but fixed.',
      execution: 'Push hips backward hinging torso forward until hamstring stretch. Drive hips forward.',
      commonMistakes: 'Rounding lower back, squatting down instead of hinging.',
      breathingCues: 'Inhale hinging down, exhale standing up.',
    },
  },
  {
    slug: 'leg-curl-machine',
    name: 'Leg Curl (Machine)',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteSlugs: ['romanian-deadlift', 'dumbbell-romanian-deadlift'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Lie face down on leg curl machine, pad adjusted against lower calves.',
      execution: 'Curl heels toward glutes, squeezing hamstrings at peak contraction. Lower with control.',
      commonMistakes: 'Lifting hips off bench to cheat.',
      breathingCues: 'Exhale curling, inhale extending.',
    },
  },
  {
    slug: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['romanian-deadlift', 'leg-curl-machine', 'hip-thrust-barbell'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Hold dumbbells in front of thighs. Soft bend in knees, shoulders back.',
      execution: 'Hinge at hips pushing glutes back as dumbbells slide down legs. Drive hips forward.',
      commonMistakes: 'Letting dumbbells drift far forward away from legs.',
      breathingCues: 'Inhale lowering, exhale driving hips forward.',
    },
  },
  {
    slug: 'hip-thrust-barbell',
    name: 'Hip Thrust (Barbell)',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['glute-bridge', 'romanian-deadlift', 'sumo-deadlift'],
    weightIncrementKg: 5.0,
    techniqueNotes: {
      setup: 'Upper back against flat bench, padded barbell across hip crease.',
      execution: 'Drive through heels to extend hips toward ceiling. Squeeze glutes hard at top.',
      commonMistakes: 'Hyperextending lower back at top instead of tucking chin and squeezing glutes.',
      breathingCues: 'Exhale thrusting up, inhale lowering.',
    },
  },
  {
    slug: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'quads'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['hip-thrust-barbell', 'romanian-deadlift', 'barbell-back-squat'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Wide stance, toes pointed out ~45 degrees, arms hanging inside knees.',
      execution: 'Drive floor away while pulling hips close to bar. Lock out by squeezing glutes.',
      commonMistakes: 'Hips shooting up early before chest rises.',
      breathingCues: 'Deep breath & brace before pull, exhale at lockout.',
    },
  },
  {
    slug: 'glute-bridge',
    name: 'Glute Bridge',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'bodyweight',
    difficultyTier: 'beginner',
    substituteSlugs: ['hip-thrust-barbell', 'romanian-deadlift'],
    weightIncrementKg: 0.0,
    techniqueNotes: {
      setup: 'Lie on back, knees bent, feet flat on floor hip-width apart.',
      execution: 'Drive through heels to raise hips into straight line with knees and shoulders.',
      commonMistakes: 'Arching lower back off floor.',
      breathingCues: 'Exhale pushing up, inhale lowering.',
    },
  },

  // ===== CALVES (2) =====
  {
    slug: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteSlugs: ['seated-calf-raise'],
    weightIncrementKg: 5.0,
    techniqueNotes: {
      setup: 'Balls of feet on platform, heels hanging over edge.',
      execution: 'Raise up on toes as high as possible, pause 1s at top, lower to deep stretch below platform.',
      commonMistakes: 'Bouncing quickly without full stretch at bottom.',
      breathingCues: 'Exhale pushing up, inhale lowering.',
    },
  },
  {
    slug: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteSlugs: ['standing-calf-raise'],
    weightIncrementKg: 5.0,
    techniqueNotes: {
      setup: 'Sit with knee pad over lower thighs, balls of feet on platform.',
      execution: 'Raise heels up high, contract soleus muscle, lower into stretch.',
      commonMistakes: 'Partial reps without full extension.',
      breathingCues: 'Exhale up, inhale down.',
    },
  },

  // ===== BICEPS (5) =====
  {
    slug: 'barbell-curl',
    name: 'Barbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['dumbbell-curl', 'hammer-curl', 'cable-curl'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Underhand shoulder-width grip on straight or EZ bar, elbows pinned at sides.',
      execution: 'Curl bar up toward chest without swinging torso. Squeeze biceps at peak.',
      commonMistakes: 'Swinging torso back and forth, letting elbows drift forward.',
      breathingCues: 'Exhale curling up, inhale lowering.',
    },
  },
  {
    slug: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['barbell-curl', 'hammer-curl', 'incline-dumbbell-curl'],
    weightIncrementKg: 2.0,
    techniqueNotes: {
      setup: 'Hold dumbbells at sides with palms facing forward.',
      execution: 'Curl dumbbells up, supinating wrists (pinkies up) near top of movement.',
      commonMistakes: 'Swinging elbows forward to cheat weight up.',
      breathingCues: 'Exhale curling, inhale lowering.',
    },
  },
  {
    slug: 'hammer-curl',
    name: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['dumbbell-curl', 'barbell-curl', 'cable-curl'],
    weightIncrementKg: 2.0,
    techniqueNotes: {
      setup: 'Hold dumbbells at sides with neutral grip (palms facing each other).',
      execution: 'Curl dumbbells keeping neutral grip throughout to target brachialis and forearm.',
      commonMistakes: 'Swinging upper body.',
      breathingCues: 'Exhale up, inhale down.',
    },
  },
  {
    slug: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['dumbbell-curl', 'barbell-curl', 'hammer-curl'],
    weightIncrementKg: 2.0,
    techniqueNotes: {
      setup: 'Sit back on bench inclined ~45 degrees, arms hanging straight down.',
      execution: 'Curl dumbbells up keeping upper arms vertical to emphasize long head stretch.',
      commonMistakes: 'Lifting shoulders off bench.',
      breathingCues: 'Exhale up, inhale down.',
    },
  },
  {
    slug: 'cable-curl',
    name: 'Cable Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteSlugs: ['barbell-curl', 'dumbbell-curl', 'hammer-curl'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Attach bar to low pulley. Stand close facing cable tower.',
      execution: 'Curl bar up keeping constant tension from cable throughout full arc.',
      commonMistakes: 'Stepping too far back from pulley.',
      breathingCues: 'Exhale curling up, inhale extending.',
    },
  },

  // ===== TRICEPS (5) =====
  {
    slug: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['tricep-pushdown-cable', 'skull-crusher', 'overhead-tricep-extension'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Lie on flat bench. Grip bar shoulder-width apart (not too narrow).',
      execution: 'Lower bar to chest keeping elbows tucked near sides. Press back up.',
      commonMistakes: 'Hands too close together (causes severe wrist strain).',
      breathingCues: 'Inhale lowering, exhale pressing.',
    },
  },
  {
    slug: 'tricep-pushdown-cable',
    name: 'Tricep Pushdown (Cable)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteSlugs: ['close-grip-bench-press', 'skull-crusher', 'overhead-tricep-extension'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Attach rope or bar to high pulley. Elbows pinned at sides.',
      execution: 'Push handle down until elbows fully extend. Squeeze triceps at bottom.',
      commonMistakes: 'Flaring elbows wide, letting shoulders roll forward.',
      breathingCues: 'Exhale pushing down, inhale returning.',
    },
  },
  {
    slug: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['tricep-pushdown-cable', 'skull-crusher', 'close-grip-bench-press'],
    weightIncrementKg: 2.0,
    techniqueNotes: {
      setup: 'Hold single dumbbell overhead with both hands under upper plate.',
      execution: 'Lower weight behind head by bending elbows. Extend back overhead.',
      commonMistakes: 'Flaring elbows out to sides.',
      breathingCues: 'Inhale lowering down, exhale extending up.',
    },
  },
  {
    slug: 'skull-crusher',
    name: 'Skull Crusher',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteSlugs: ['tricep-pushdown-cable', 'overhead-tricep-extension', 'close-grip-bench-press'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Lie on flat bench holding EZ-bar over chest at arm length.',
      execution: 'Lower bar toward forehead by bending elbows only. Extend elbows to start.',
      commonMistakes: 'Moving upper arms back and forth during movement.',
      breathingCues: 'Inhale lowering, exhale extending.',
    },
  },
  {
    slug: 'tricep-dip-bench',
    name: 'Tricep Dip (Bench)',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    difficultyTier: 'beginner',
    substituteSlugs: ['tricep-pushdown-cable', 'close-grip-bench-press'],
    weightIncrementKg: 0.0,
    techniqueNotes: {
      setup: 'Hands on bench edge behind hips, feet extended forward on floor.',
      execution: 'Lower body by bending elbows to 90 degrees. Press back up to lockout.',
      commonMistakes: 'Dipping too low causing shoulder strain.',
      breathingCues: 'Inhale descending, exhale pressing up.',
    },
  },

  // ===== CORE (5) =====
  {
    slug: 'plank',
    name: 'Plank',
    primaryMuscle: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    difficultyTier: 'beginner',
    substituteSlugs: ['dead-bug', 'cable-crunch', 'ab-wheel-rollout'],
    weightIncrementKg: 0.0,
    techniqueNotes: {
      setup: 'Forearms and toes on floor, elbows under shoulders.',
      execution: 'Hold straight body line from head to heels, bracing core and glutes.',
      commonMistakes: 'Hips sagging down or piking up in air.',
      breathingCues: 'Breathe steadily, do not hold breath.',
    },
  },
  {
    slug: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficultyTier: 'intermediate',
    substituteSlugs: ['plank', 'cable-crunch', 'hanging-leg-raise'],
    weightIncrementKg: 0.0,
    techniqueNotes: {
      setup: 'Kneel holding ab wheel under shoulders on floor.',
      execution: 'Roll wheel forward extending torso while maintaining slight pelvic tuck. Pull back.',
      commonMistakes: 'Hyperextending lower back into arch.',
      breathingCues: 'Inhale rolling out, exhale pulling back.',
    },
  },
  {
    slug: 'cable-crunch',
    name: 'Cable Crunch',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteSlugs: ['ab-wheel-rollout', 'hanging-leg-raise', 'plank'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Kneel under high cable holding rope attachment by sides of head.',
      execution: 'Flex spine to crunch ribcage toward pelvis. Squeeze abs at bottom.',
      commonMistakes: 'Pulling rope with arms instead of flexing abdominal wall.',
      breathingCues: 'Exhale crunching down, inhale returning.',
    },
  },
  {
    slug: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficultyTier: 'intermediate',
    substituteSlugs: ['cable-crunch', 'ab-wheel-rollout', 'dead-bug'],
    weightIncrementKg: 0.0,
    techniqueNotes: {
      setup: 'Hang from pull-up bar with straight arms and legs.',
      execution: 'Raise knees or straight legs up to hip height by flexing waist. Lower slowly.',
      commonMistakes: 'Swinging legs for momentum.',
      breathingCues: 'Exhale raising legs, inhale lowering.',
    },
  },
  {
    slug: 'dead-bug',
    name: 'Dead Bug',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficultyTier: 'beginner',
    substituteSlugs: ['plank', 'cable-crunch'],
    weightIncrementKg: 0.0,
    techniqueNotes: {
      setup: 'Lie on back, arms pointing up, knees bent 90 degrees in tabletop position.',
      execution: 'Lower opposite arm and leg toward floor while pressing lower back flat into floor.',
      commonMistakes: 'Lower back arching up off floor.',
      breathingCues: 'Exhale extending limbs, inhale returning to center.',
    },
  },

  // ===== TRAPS & FOREARMS (4) =====
  {
    slug: 'barbell-shrug',
    name: 'Barbell Shrug',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'barbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['dumbbell-shrug', 'face-pull'],
    weightIncrementKg: 5.0,
    techniqueNotes: {
      setup: 'Stand holding barbell at thigh level with overhand grip.',
      execution: 'Elevate shoulders straight up toward ears, hold contraction 1s, lower slowly.',
      commonMistakes: 'Rolling shoulders in circles (causes joint wear), jerking weight.',
      breathingCues: 'Exhale shrugging up, inhale lowering.',
    },
  },
  {
    slug: 'dumbbell-shrug',
    name: 'Dumbbell Shrug',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['barbell-shrug', 'face-pull'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Stand holding heavy dumbbells at sides.',
      execution: 'Shrug shoulders straight up toward ears, squeeze traps at top.',
      commonMistakes: 'Bending elbows to assist lift.',
      breathingCues: 'Exhale shrugging up, inhale lowering.',
    },
  },
  {
    slug: 'reverse-barbell-curl',
    name: 'Reverse Barbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['hammer-curl', 'wrist-curl'],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Grip bar with overhand (pronated) grip shoulder-width apart.',
      execution: 'Curl bar up focusing on brachioradialis and forearm muscles.',
      commonMistakes: 'Swinging hips, wrists collapsing downward.',
      breathingCues: 'Exhale curling up, inhale lowering.',
    },
  },
  {
    slug: 'wrist-curl',
    name: 'Wrist Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteSlugs: ['reverse-barbell-curl', 'hammer-curl'],
    weightIncrementKg: 1.0,
    techniqueNotes: {
      setup: 'Seated, forearms resting flat on thighs, wrists hanging over knees holding dumbbells palms up.',
      execution: 'Curl dumbbells upward using wrists only, lower to full extension.',
      commonMistakes: 'Lifting forearms off legs.',
      breathingCues: 'Exhale curling, inhale lowering.',
    },
  },
];

export async function seedExercises(): Promise<void> {
  const count = await db.exercises.count();
  if (count >= 50) return; // Already seeded with 50+

  // If count > 0 but < 50, clear to reseed cleanly with stable slugs
  if (count > 0) {
    await db.exercises.clear();
  }

  // Insert base exercises without substituteIds first to get auto-increment IDs
  const dummyExercises: Omit<Exercise, 'id'>[] = EXERCISES_SEED.map((ex) => ({
    slug: ex.slug,
    name: ex.name,
    primaryMuscle: ex.primaryMuscle,
    secondaryMuscles: ex.secondaryMuscles,
    equipment: ex.equipment,
    difficultyTier: ex.difficultyTier,
    substituteIds: [],
    substituteSlugs: ex.substituteSlugs,
    techniqueNotes: ex.techniqueNotes,
    weightIncrementKg: ex.weightIncrementKg,
  }));

  await db.exercises.bulkAdd(dummyExercises as Exercise[]);

  // Query all inserted exercises to map slug -> id
  const inserted = await db.exercises.toArray();
  const slugToIdMap = new Map<string, number>();
  inserted.forEach((ex) => {
    if (ex.slug && ex.id) {
      slugToIdMap.set(ex.slug, ex.id);
    }
  });

  // Update substituteIds based on substituteSlugs
  for (const ex of inserted) {
    if (ex.id && ex.substituteSlugs) {
      const subIds = ex.substituteSlugs
        .map((slug) => slugToIdMap.get(slug))
        .filter((id): id is number => id !== undefined);

      await db.exercises.update(ex.id, { substituteIds: subIds });
    }
  }
}

export { EXERCISES_SEED };
