import { db } from './db';
import type { Exercise } from './schema';

const EXERCISES: Omit<Exercise, 'id'>[] = [
  // ===== CHEST =====
  {
    name: 'Barbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    difficultyTier: 'beginner',
    substituteIds: [2, 3, 5],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Lie flat on bench, eyes under bar. Grip slightly wider than shoulder-width. Retract shoulder blades. Feet flat.',
      execution: 'Lower to mid-chest with control (2-3s). Press straight up to lockout.',
      commonMistakes: 'Bouncing off chest, flaring elbows 90 degrees, lifting hips off bench.',
      breathingCues: 'Inhale on the way down, exhale forcefully as you press.',
    },
  },
  {
    name: 'Incline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteIds: [1, 3, 4],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Set bench to 30-45 degrees. Kick dumbbells up to shoulder level.',
      execution: 'Press overhead in a gentle arc. Lower under control to chest level.',
      commonMistakes: 'Incline too steep (becomes shoulder press), letting shoulders roll forward.',
      breathingCues: 'Inhale on descent, exhale on press.',
    },
  },
  {
    name: 'Dumbbell Chest Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteIds: [4, 1, 2],
    weightIncrementKg: 2,
    techniqueNotes: {
      setup: 'Lie flat on bench. Hold dumbbells over chest with slight elbow bend.',
      execution: 'Lower in a wide arc until chest stretch is felt. Hug together at top.',
      commonMistakes: 'Bending elbows too much (making it a press), going too deep.',
      breathingCues: 'Inhale on arc down, exhale on squeeze up.',
    },
  },
  {
    name: 'Cable Crossover',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteIds: [3, 2, 5],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Set pulleys high or mid height. Step forward, slight lean.',
      execution: 'Bring handles together in front of lower chest in a hugging motion.',
      commonMistakes: 'Using momentum, straightening arms completely.',
      breathingCues: 'Exhale bringing together, inhale returning.',
    },
  },
  {
    name: 'Chest Dip',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    difficultyTier: 'intermediate',
    substituteIds: [1, 2, 3],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Grip dip bars. Lean torso forward 30 degrees to target chest.',
      execution: 'Lower until shoulders are below elbows. Drive back up.',
      commonMistakes: 'Staying upright (hits triceps), shrugging shoulders.',
      breathingCues: 'Inhale descending, exhale pressing up.',
    },
  },

  // ===== BACK =====
  {
    name: 'Barbell Bent-Over Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteIds: [7, 8, 10],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Hinge at hips 45 degrees, flat back, overhand grip.',
      execution: 'Pull bar to lower sternum, driving elbows back. Lower under control.',
      commonMistakes: 'Rounding lower back, standing up using momentum.',
      breathingCues: 'Exhale on pull, inhale lowering.',
    },
  },
  {
    name: 'Dumbbell Single-Arm Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteIds: [6, 8, 10],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Support knee and hand on bench. Dumbbell in opposite hand.',
      execution: 'Pull dumbbell to hip, driving elbow back. Lower to full stretch.',
      commonMistakes: 'Torso rotation, shrugging shoulder.',
      breathingCues: 'Exhale pulling up, inhale lowering.',
    },
  },
  {
    name: 'Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteIds: [9, 6, 10],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Grip bar wide, thighs secured under pad, slight lean back.',
      execution: 'Pull bar to upper chest, squeezing lats. Control the return.',
      commonMistakes: 'Pulling behind neck, leaning back too far.',
      breathingCues: 'Exhale on pull, inhale on rise.',
    },
  },
  {
    name: 'Pull-Up',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    difficultyTier: 'intermediate',
    substituteIds: [8, 6, 7],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Overhand grip, shoulder-width or wider on pull-up bar.',
      execution: 'Pull chin over bar. Lower to full dead hang with elbows straight.',
      commonMistakes: 'Kipping/swinging, partial range at bottom.',
      breathingCues: 'Exhale pulling up, inhale lowering down.',
    },
  },
  {
    name: 'Seated Cable Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteIds: [6, 7, 8],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Feet on pads, upright stance, hold v-bar attachment.',
      execution: 'Pull handle to abdomen while driving shoulder blades back.',
      commonMistakes: 'Swinging back and forth excessively.',
      breathingCues: 'Exhale pulling in, inhale extending.',
    },
  },
  {
    name: 'Face Pull',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteIds: [13, 14, 15],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Attach rope at high position on cable tower.',
      execution: 'Pull rope toward forehead, flaring hands out at ears.',
      commonMistakes: 'Too heavy weight, pulling to throat instead of face.',
      breathingCues: 'Exhale pulling back, inhale returning.',
    },
  },

  // ===== SHOULDERS =====
  {
    name: 'Overhead Press (Barbell)',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteIds: [13, 15, 12],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Grip shoulder-width, bar resting on upper chest.',
      execution: 'Press overhead until elbows lock out. Head moves through at top.',
      commonMistakes: 'Arching lower back excessively, pressing bar forward.',
      breathingCues: 'Brace before press, exhale at top.',
    },
  },
  {
    name: 'Dumbbell Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteIds: [11, 14, 15],
    weightIncrementKg: 1,
    techniqueNotes: {
      setup: 'Stand holding dumbbells at sides, slight elbow bend.',
      execution: 'Raise arms out to sides until parallel with floor. Lead with elbows.',
      commonMistakes: 'Swinging weight up, shrugging traps.',
      breathingCues: 'Exhale raising up, inhale lowering.',
    },
  },
  {
    name: 'Rear Delt Dumbbell Fly',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteIds: [11, 13, 15],
    weightIncrementKg: 1,
    techniqueNotes: {
      setup: 'Hinge forward 90 degrees or sit on edge of bench bent over.',
      execution: 'Raise arms out to sides in wide arc targeting rear delts.',
      commonMistakes: 'Bending elbows into a row, using momentum.',
      breathingCues: 'Exhale raising, inhale lowering.',
    },
  },
  {
    name: 'Arnold Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    difficultyTier: 'intermediate',
    substituteIds: [12, 13, 11],
    weightIncrementKg: 2,
    techniqueNotes: {
      setup: 'Sit upright, dumbbells at chest with palms facing you.',
      execution: 'Rotate palms outward as you press overhead.',
      commonMistakes: 'Rushing rotation, arching lower back.',
      breathingCues: 'Exhale pressing up, inhale lowering.',
    },
  },

  // ===== QUADS =====
  {
    name: 'Barbell Back Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteIds: [17, 18, 19],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Bar on upper traps, feet shoulder-width, toes angled slightly out.',
      execution: 'Sit back and down until thighs are parallel to floor. Drive up.',
      commonMistakes: 'Knees caving in, heels lifting off floor.',
      breathingCues: 'Inhale & brace at top, hold down, exhale coming up.',
    },
  },
  {
    name: 'Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteIds: [16, 18, 19],
    weightIncrementKg: 5,
    techniqueNotes: {
      setup: 'Sit in machine, feet mid-platform shoulder-width apart.',
      execution: 'Lower sled to 90 degree knee bend. Press back up without locking knees.',
      commonMistakes: 'Locking knees hard, tailbone lifting off seat.',
      breathingCues: 'Inhale lowering, exhale pushing.',
    },
  },
  {
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    difficultyTier: 'intermediate',
    substituteIds: [16, 17, 19],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Back foot elevated on bench, front foot stepped forward.',
      execution: 'Lower back knee toward floor while staying upright. Drive up.',
      commonMistakes: 'Front knee pushing too far forward over toes.',
      breathingCues: 'Inhale lowering, exhale driving up.',
    },
  },
  {
    name: 'Leg Extension',
    primaryMuscle: 'quads',
    secondaryMuscles: [],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteIds: [16, 17, 18],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Pad on lower shins, knees aligned with machine pivot.',
      execution: 'Extend legs straight out, squeeze quads at top. Lower slowly.',
      commonMistakes: 'Kicking weight up with momentum.',
      breathingCues: 'Exhale extending, inhale lowering.',
    },
  },

  // ===== HAMSTRINGS & GLUTES =====
  {
    name: 'Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteIds: [21, 22, 23],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Stand holding bar, feet hip-width, knees soft but fixed.',
      execution: 'Push hips back hinging forward until hamstring stretch. Drive hips forward.',
      commonMistakes: 'Rounding lower back, squatting down.',
      breathingCues: 'Inhale hinging down, exhale standing up.',
    },
  },
  {
    name: 'Leg Curl (Machine)',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteIds: [20, 22, 23],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Lie face down, pad against lower calves.',
      execution: 'Curl heels toward glutes, squeeze hamstrings at peak.',
      commonMistakes: 'Lifting hips off bench to cheat.',
      breathingCues: 'Exhale curling, inhale extending.',
    },
  },
  {
    name: 'Hip Thrust (Barbell)',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteIds: [20, 21, 23],
    weightIncrementKg: 5,
    techniqueNotes: {
      setup: 'Upper back on bench, barbell resting on hip crease.',
      execution: 'Drive through heels to lift hips parallel to floor. Squeeze glutes.',
      commonMistakes: 'Arching lower back instead of driving through glutes.',
      breathingCues: 'Exhale thrusting up, inhale lowering down.',
    },
  },
  {
    name: 'Sumo Deadlift',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'quads'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteIds: [20, 21, 22],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Wide stance, toes out 45 degrees, hands inside knees.',
      execution: 'Drive floor away with legs while opening knees out. Stand tall.',
      commonMistakes: 'Hips shooting up early.',
      breathingCues: 'Brace before lift, exhale at lockout.',
    },
  },

  // ===== CALVES =====
  {
    name: 'Standing Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteIds: [25],
    weightIncrementKg: 5,
    techniqueNotes: {
      setup: 'Balls of feet on platform, heels hanging free.',
      execution: 'Raise up onto toes as high as possible, hold 1s, lower to deep stretch.',
      commonMistakes: 'Bouncing without full stretch at bottom.',
      breathingCues: 'Exhale pushing up, inhale lowering.',
    },
  },
  {
    name: 'Seated Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    difficultyTier: 'beginner',
    substituteIds: [24],
    weightIncrementKg: 5,
    techniqueNotes: {
      setup: 'Seated with pads on thighs, balls of feet on platform.',
      execution: 'Raise heels up high, contract calves, lower to full stretch.',
      commonMistakes: 'Using short partial reps.',
      breathingCues: 'Exhale up, inhale down.',
    },
  },

  // ===== BICEPS =====
  {
    name: 'Barbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    difficultyTier: 'beginner',
    substituteIds: [27, 28, 30],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Underhand shoulder-width grip, elbows tucked at sides.',
      execution: 'Curl bar up to shoulders without moving elbows forward.',
      commonMistakes: 'Swinging torso for momentum.',
      breathingCues: 'Exhale curling up, inhale lowering down.',
    },
  },
  {
    name: 'Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteIds: [26, 28, 30],
    weightIncrementKg: 2,
    techniqueNotes: {
      setup: 'Hold dumbbells at sides, palms facing forward.',
      execution: 'Curl weights up toward shoulders, supinating wrists at top.',
      commonMistakes: 'Elbows swinging forward.',
      breathingCues: 'Exhale curling, inhale lowering.',
    },
  },
  {
    name: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteIds: [26, 27, 30],
    weightIncrementKg: 2,
    techniqueNotes: {
      setup: 'Palms facing each other (neutral grip) at sides.',
      execution: 'Curl dumbbells keeping neutral grip throughout.',
      commonMistakes: 'Swinging arms.',
      breathingCues: 'Exhale up, inhale down.',
    },
  },
  {
    name: 'Incline Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteIds: [26, 27, 28],
    weightIncrementKg: 2,
    techniqueNotes: {
      setup: 'Sit back on bench inclined 45 degrees, arms hanging straight.',
      execution: 'Curl up while keeping upper arms vertical.',
      commonMistakes: 'Lifting shoulders off bench.',
      breathingCues: 'Exhale up, inhale down.',
    },
  },
  {
    name: 'Cable Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteIds: [26, 27, 28],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Low cable attachment with straight or ez-bar.',
      execution: 'Curl bar up keeping constant tension from cable.',
      commonMistakes: 'Stepping too far back.',
      breathingCues: 'Exhale curling up, inhale extending.',
    },
  },

  // ===== TRICEPS =====
  {
    name: 'Close-Grip Bench Press',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteIds: [32, 33, 34],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Bench press setup with hands shoulder-width apart.',
      execution: 'Lower bar keeping elbows tucked close to sides. Press up.',
      commonMistakes: 'Hands too close (causes wrist pain).',
      breathingCues: 'Inhale lowering, exhale pressing.',
    },
  },
  {
    name: 'Tricep Pushdown (Cable)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteIds: [31, 33, 34],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'High cable attachment with rope or bar.',
      execution: 'Push down until elbows fully extend. Keep upper arms pinned.',
      commonMistakes: 'Flaring elbows, letting shoulders move.',
      breathingCues: 'Exhale pushing down, inhale returning.',
    },
  },
  {
    name: 'Overhead Tricep Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficultyTier: 'beginner',
    substituteIds: [31, 32, 34],
    weightIncrementKg: 2,
    techniqueNotes: {
      setup: 'Hold dumbbell overhead with both hands.',
      execution: 'Lower weight behind head by bending elbows. Extend back up.',
      commonMistakes: 'Flaring elbows wide.',
      breathingCues: 'Inhale down, exhale extending up.',
    },
  },
  {
    name: 'Skull Crusher',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    difficultyTier: 'intermediate',
    substituteIds: [31, 32, 33],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Lie on bench holding ez-bar overhead.',
      execution: 'Lower bar toward forehead by bending elbows only. Extend.',
      commonMistakes: 'Moving upper arms back and forth.',
      breathingCues: 'Inhale lowering, exhale extending.',
    },
  },

  // ===== CORE =====
  {
    name: 'Plank',
    primaryMuscle: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    difficultyTier: 'beginner',
    substituteIds: [36, 37, 38],
    weightIncrementKg: 0,
    techniqueNotes: {
      setup: 'Forearms and toes on floor, body in straight line.',
      execution: 'Hold position tight squeezing glutes and abs.',
      commonMistakes: 'Hips sagging down or piking up.',
      breathingCues: 'Breathe steadily, do not hold breath.',
    },
  },
  {
    name: 'Ab Wheel Rollout',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficultyTier: 'intermediate',
    substituteIds: [35, 37, 38],
    weightIncrementKg: 0,
    techniqueNotes: {
      setup: 'Kneel holding ab wheel under shoulders.',
      execution: 'Roll wheel forward extending body. Pull back using abs.',
      commonMistakes: 'Lower back sagging into arch.',
      breathingCues: 'Inhale rolling out, exhale pulling back.',
    },
  },
  {
    name: 'Cable Crunch',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'cable',
    difficultyTier: 'beginner',
    substituteIds: [35, 36, 38],
    weightIncrementKg: 2.5,
    techniqueNotes: {
      setup: 'Kneel under high cable holding rope behind head.',
      execution: 'Crunch elbows toward knees by flexing abs. Return.',
      commonMistakes: 'Pulling with arms instead of abs.',
      breathingCues: 'Exhale crunching down, inhale coming up.',
    },
  },
  {
    name: 'Hanging Leg Raise',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficultyTier: 'intermediate',
    substituteIds: [35, 36, 37],
    weightIncrementKg: 0,
    techniqueNotes: {
      setup: 'Hang from pull-up bar.',
      execution: 'Raise knees or straight legs up to 90 degrees. Lower slow.',
      commonMistakes: 'Swinging body for momentum.',
      breathingCues: 'Exhale raising, inhale lowering.',
    },
  },
  {
    name: 'Dead Bug',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficultyTier: 'beginner',
    substituteIds: [35, 36, 37],
    weightIncrementKg: 0,
    techniqueNotes: {
      setup: 'Lie on back, arms up, legs at 90 degrees.',
      execution: 'Lower opposite arm and leg toward floor while pressing low back down.',
      commonMistakes: 'Arching lower back off floor.',
      breathingCues: 'Exhale extending, inhale returning.',
    },
  },
];

export async function seedExercises(): Promise<void> {
  const count = await db.exercises.count();
  if (count > 0) return; // Already seeded
  await db.exercises.bulkAdd(EXERCISES as Exercise[]);
}

export { EXERCISES };
